--- #YAML:1.0
name:               cPanel-PublicAPI
version:            1.002
abstract:           A perl interface for interacting with cPanel
author:
    - cPanel, Inc. <integration@cpanel.net>
license:            Modified BSD
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket::INET:  1.31
    IO::Socket::SSL:   1.33
    JSON::XS:          2
    Test::More:        0
    URI::Escape:       3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
